# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/template-project-nbdev',
                'doc_host': 'https://felidz.github.io',
                'git_url': 'https://github.com/felidz/template-project-nbdev',
                'lib_path': 'template_project_nbdev'},
  'syms': {'template_project_nbdev.core': {'template_project_nbdev.core.foo': ('core.html#foo', 'template_project_nbdev/core.py')}}}
