
project:
  type: website


format:
  html:
    toc: true
    code-tools: 
      source: true
      caption: none
    code-fold: true
    code-summary: "Code"
    code-line-numbers: true
    css: styles.css
    theme: 
      light: cosmo
      dark: solar
    highlight-style: github


website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]