
metadata-files: [nbdev.yml]
bibliography: references.bib
reference-location: margin
# citation: true

project:
  type: website
  preview:
    port: 3000

format:
  html:
    toc: true
    code-tools: 
      source: true
      # caption: none
    code-fold: true
    code-summary: "Code"
    code-line-numbers: true
    css: styles.css
    theme: 
      light: cosmo
      dark: solar
    highlight-style: github

website:
  twitter-card: true
  open-graph: true
  navbar:
    background: primary
    search: true
    left:
      - icon: github
        href: https://github.com/felidz/template-project-nbdev
        aria-label: GitHub
  page-navigation: true
  sidebar:
      style: floating
      contents:
        - index.ipynb
        # - auto: "*.ipynb"
        - section: Tutorials
          contents: tutorials/*
        - section: How-tos
          contents: how-tos/*
        - section: Whys
          contents: whys/*
        - section: FAQ
          contents: faq/*
        - section: Examples
          contents: examples/*
        - section: API
          contents: api/*