# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_module.submodule.ipynb.

# %% auto 0
__all__ = ['Foo']

# %% ../../nbs/01_module.submodule.ipynb 4
class Foo:
    def __init__(self):
        pass 
    
    def bar(self):
        print("bar")


